# Site settings
title: Florian Schäffeler
email: hello@fschaeffeler.de
description: Hallo. Mein Name ist Florian Schäffeler und ich bein ein Software Entwickler aus Ravensburg.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.fschaeffeler.de" # the base hostname & protocol for your site

# Identity
your-name: Florian Schäffeler
your-title: Software Entwickler
skills: Web, Python, C++, Continous Integration


# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/robertobernabe
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
