# Site settings
title: Florian Escribano - Software Entwicklung Überlingen
email: florian@escribano.de
description: Hallo. Mein Name ist Florian Escribano und ich bin ein Software Entwickler / Build Engineer aus Überlingen.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://florian.escribano.de" # the base hostname & protocol for your site

# Identity
your-name: Florian Escribano
your-title: DevOps Engineer, Software Entwickler / Build Engineer
skills: DevOps, Python, Continous Integration

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/robertobernabe/
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/robertobernabe
pinterest_url:
slack_url:
twitter_url:
linkedin_url: https://www.linkedin.com/in/florian-schäffeler-05123367
xing_url: https://www.xing.com/profile/Florian_Schaeffeler2/cv

# Build settings
markdown: kramdown
